// Code generated by goenum; DO NOT EDIT.

package status

import (
	"encoding/json"
	"fmt"
	goenum "github.com/abdorrahmani/goenum"
	"strconv"
	"strings"
)

var permissionInfo = goenum.Register(goenum.EnumInfo[Permission]{
	Names:  []string{"READ", "WRITE", "DELETE"},
	Values: []Permission{PermissionRead, PermissionWrite, PermissionDelete},
})

// PermissionKnownMask has one bit for every declared flag.
const permissionKnownMask = Permission(1 | 2 | 4)

// String renders the flag set as canonical names joined with "|", e.g.
// "READ|WRITE". The zero value renders as "0"; undeclared bits render as
// "Permission(<bits>)".
func (p Permission) String() string {
	if p == 0 {
		return "0"
	}
	var out []string
	rest := uint64(p)
	names := permissionInfo.AllNames()
	for i, v := range permissionInfo.All() {
		bit := uint64(v)
		if rest&bit != 0 {
			out = append(out, names[i])
			rest &^= bit
		}
	}
	if rest != 0 {
		out = append(out, "Permission("+strconv.FormatUint(rest, 10)+")")
	}
	return strings.Join(out, "|")
}

// IsValid reports whether every bit set in p is a declared flag. The zero
// value (no flags) is valid.
func (p Permission) IsValid() bool {
	return p&^permissionKnownMask == 0
}

// IsEmpty reports whether no flags are set.
func (p Permission) IsEmpty() bool { return p == 0 }

// Has reports whether every flag in other is set.
func (p Permission) Has(other Permission) bool { return p&other == other }

// Add returns the union of the flags.
func (p Permission) Add(other Permission) Permission { return p | other }

// Remove returns the flags without those in other.
func (p Permission) Remove(other Permission) Permission { return p &^ other }

// Description returns the description declared for the single flag p, or
// "" for combinations and undeclared values.
func (p Permission) Description() string { return permissionInfo.Description(p) }

// Aliases returns the aliases declared for the single flag p.
func (p Permission) Aliases() []string { return permissionInfo.AliasesOf(p) }

// HasAlias reports whether alias belongs to the single flag p.
func (p Permission) HasAlias(alias string) bool { return permissionInfo.HasAlias(p, alias) }

// ParsePermission resolves a "|"-separated list of canonical names or aliases
// (case-insensitive) into a combined flag set. "0" yields the zero value.
func ParsePermission(name string) (Permission, error) {
	if name == "0" {
		return 0, nil
	}
	var out Permission
	for _, part := range strings.Split(name, "|") {
		v, ok := permissionInfo.Lookup(strings.TrimSpace(part))
		if !ok {
			return 0, fmt.Errorf("%w: %q for Permission", goenum.ErrUnknownEnum, part)
		}
		out |= v
	}
	return out, nil
}

// MustParsePermission is ParsePermission but panics on unknown names.
func MustParsePermission(name string) Permission {
	v, err := ParsePermission(name)
	if err != nil {
		panic(err)
	}
	return v
}

// PermissionFromValue converts an underlying bit pattern to a Permission and reports
// whether every bit is declared.
func PermissionFromValue(v uint64) (Permission, bool) {
	e := Permission(v)
	return e, e.IsValid()
}

// MarshalJSON encodes the flag set as its String form.
func (p Permission) MarshalJSON() ([]byte, error) {
	if !p.IsValid() {
		return nil, fmt.Errorf("goenum: cannot marshal undeclared Permission value")
	}
	return json.Marshal(p.String())
}

// UnmarshalJSON decodes a "|"-separated name list into p.
func (p *Permission) UnmarshalJSON(data []byte) error {
	var name string
	if err := json.Unmarshal(data, &name); err != nil {
		return err
	}
	v, err := ParsePermission(name)
	if err != nil {
		return err
	}
	*p = v
	return nil
}

// MarshalText implements encoding.TextMarshaler.
func (p Permission) MarshalText() ([]byte, error) {
	if !p.IsValid() {
		return nil, fmt.Errorf("goenum: cannot marshal undeclared Permission value")
	}
	return []byte(p.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (p *Permission) UnmarshalText(data []byte) error {
	v, err := ParsePermission(string(data))
	if err != nil {
		return err
	}
	*p = v
	return nil
}

// Value implements database/sql/driver.Valuer, storing the bit pattern.
func (p Permission) Value() (any, error) {
	if !p.IsValid() {
		return nil, fmt.Errorf("goenum: cannot store undeclared Permission value")
	}
	return int64(p), nil
}

// Scan implements sql.Scanner.
func (p *Permission) Scan(src any) error {
	switch v := src.(type) {
	case nil:
		*p = 0
		return nil
	case int64:
		e := Permission(v)
		if !e.IsValid() {
			return fmt.Errorf("goenum: cannot scan value %d into Permission", v)
		}
		*p = e
		return nil
	case string:
		return p.UnmarshalText([]byte(v))
	case []byte:
		return p.UnmarshalText(v)
	}
	return fmt.Errorf("goenum: cannot scan %T into Permission", src)
}
