// Code generated by goenum; DO NOT EDIT.

package status

import (
	"encoding/json"
	"fmt"
	goenum "github.com/abdorrahmani/goenum"
	"strconv"
)

var priorityInfo = goenum.Register(goenum.EnumInfo[Priority]{
	Names:  []string{"LOW", "MEDIUM", "HIGH"},
	Values: []Priority{PriorityLow, PriorityMedium, PriorityHigh},
	Descs:  []string{"Low priority task", "Medium priority task", "High priority task"},
	Aliases: [][]string{
		{},
		{},
		{"URGENT"},
	},
})

// String returns the canonical name of p, or "Priority(<value>)" for
// undeclared values.
func (p Priority) String() string {
	if name, ok := priorityInfo.Name(p); ok {
		return name
	}
	return "Priority(" + strconv.Quote(string(p)) + ")"
}

// IsValid reports whether p is one of the declared Priority values.
func (p Priority) IsValid() bool {
	_, ok := priorityInfo.Name(p)
	return ok
}

// Description returns the description declared for p, or "" when p is
// undeclared or has no description.
func (p Priority) Description() string { return priorityInfo.Description(p) }

// Aliases returns the aliases declared for p.
func (p Priority) Aliases() []string { return priorityInfo.AliasesOf(p) }

// HasAlias reports whether alias belongs to p (compared case-insensitively).
func (p Priority) HasAlias(alias string) bool { return priorityInfo.HasAlias(p, alias) }

// ParsePriority resolves a canonical name or alias to a Priority value,
// case-insensitively. It returns an error wrapping goenum.ErrUnknownEnum for
// unknown names.
func ParsePriority(name string) (Priority, error) {
	v, ok := priorityInfo.Lookup(name)
	if !ok {
		return "", fmt.Errorf("%w: %q for Priority", goenum.ErrUnknownEnum, name)
	}
	return v, nil
}

// MustParsePriority is ParsePriority but panics on unknown names. Use it only for
// inputs known to be valid.
func MustParsePriority(name string) Priority {
	v, err := ParsePriority(name)
	if err != nil {
		panic(err)
	}
	return v
}

// PriorityFromValue converts an underlying value to a Priority and reports whether
// it is declared.
func PriorityFromValue(v string) (Priority, bool) {
	e := Priority(v)
	return e, e.IsValid()
}

// MarshalJSON encodes p as its canonical JSON name. Undeclared values are
// a marshaling error so invalid data never round-trips silently.
func (p Priority) MarshalJSON() ([]byte, error) {
	name, ok := priorityInfo.Name(p)
	if !ok {
		return nil, fmt.Errorf("goenum: cannot marshal undeclared Priority value")
	}
	return json.Marshal(name)
}

// UnmarshalJSON decodes a canonical name or alias into p.
func (p *Priority) UnmarshalJSON(data []byte) error {
	var name string
	if err := json.Unmarshal(data, &name); err != nil {
		return err
	}
	v, err := ParsePriority(name)
	if err != nil {
		return err
	}
	*p = v
	return nil
}

// MarshalText implements encoding.TextMarshaler.
func (p Priority) MarshalText() ([]byte, error) {
	name, ok := priorityInfo.Name(p)
	if !ok {
		return nil, fmt.Errorf("goenum: cannot marshal undeclared Priority value")
	}
	return []byte(name), nil
}

// UnmarshalText implements encoding.TextUnmarshaler, accepting canonical
// names and aliases.
func (p *Priority) UnmarshalText(data []byte) error {
	v, err := ParsePriority(string(data))
	if err != nil {
		return err
	}
	*p = v
	return nil
}

// Value implements database/sql/driver.Valuer, storing the underlying value.
func (p Priority) Value() (any, error) {
	if !p.IsValid() {
		return nil, fmt.Errorf("goenum: cannot store undeclared Priority value")
	}
	return string(p), nil
}

// Scan implements sql.Scanner, accepting nil, the underlying numeric/string
// type and canonical names or aliases.
func (p *Priority) Scan(src any) error {
	switch v := src.(type) {
	case nil:
		*p = ""
		return nil
	case string:
		return p.UnmarshalText([]byte(v))
	case []byte:
		return p.UnmarshalText(v)
	}
	return fmt.Errorf("goenum: cannot scan %T into Priority", src)
}
