package generator

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"
)

// goenumImport is the import path of the runtime package used by generated
// code.
const goenumImport = "github.com/abdorrahmani/goenum"

// Render produces the generated file name and gofmt-formatted source for one
// enum. Output is deterministic: identical inputs always produce byte-identical
// files.
func Render(e *Enum, pkgName string) (string, []byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by goenum; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkgName)

	needsStrings := e.Flags
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	fmt.Fprintf(&b, "\tgoenum %q\n", goenumImport)
	b.WriteString("\t\"strconv\"\n")
	if needsStrings {
		b.WriteString("\t\"strings\"\n")
	}
	b.WriteString(")\n\n")

	recv := receiverName(e.TypeName)
	info := lowerFirst(e.TypeName) + "Info"

	// Metadata table.
	fmt.Fprintf(&b, "var %s = goenum.Register(goenum.EnumInfo[%s]{\n", info, e.TypeName)
	b.WriteString("\tNames: []string{")
	writeStrings(&b, e.Names())
	b.WriteString("},\n")
	b.WriteString("\tValues: []" + e.TypeName + "{")
	for i, v := range e.Values {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(v.Ident)
	}
	b.WriteString("},\n")
	if hasAny(e, func(v Value) bool { return v.Desc != "" }) {
		b.WriteString("\tDescs: []string{")
		writeStrings(&b, e.Descs())
		b.WriteString("},\n")
	}
	if hasAny(e, func(v Value) bool { return len(v.Aliases) > 0 }) {
		b.WriteString("\tAliases: [][]string{\n")
		for _, v := range e.Values {
			b.WriteString("\t\t{")
			writeStrings(&b, v.Aliases)
			b.WriteString("},\n")
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("})\n\n")

	if e.Flags {
		renderFlags(&b, e, recv, info)
	} else {
		renderScalar(&b, e, recv, info)
	}

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", nil, fmt.Errorf("goenum: generated code for %s does not format: %w\n%s", e.TypeName, err, b.String())
	}
	return lowerFirst(e.TypeName) + genFileSuffix, src, nil
}

func renderScalar(b *strings.Builder, e *Enum, recv, info string) {
	t := e.TypeName
	zero := "0"
	numConv := "int64(" + recv + ")"
	strConv := "strconv.FormatInt(" + numConv + ", 10)"
	if e.Kind == KindString {
		zero = `""`
		numConv = "string(" + recv + ")"
		strConv = "strconv.Quote(" + numConv + ")"
	}

	fmt.Fprintf(b, `
// String returns the canonical name of %[1]s, or "%[2]s(<value>)" for
// undeclared values.
func (%[3]s %[2]s) String() string {
	if name, ok := %[4]s.Name(%[3]s); ok {
		return name
	}
	return "%[2]s(" + %[5]s + ")"
}

// IsValid reports whether %[3]s is one of the declared %[2]s values.
func (%[3]s %[2]s) IsValid() bool {
	_, ok := %[4]s.Name(%[3]s)
	return ok
}

// Description returns the description declared for %[3]s, or "" when %[3]s is
// undeclared or has no description.
func (%[3]s %[2]s) Description() string { return %[4]s.Description(%[3]s) }

// Aliases returns the aliases declared for %[3]s.
func (%[3]s %[2]s) Aliases() []string { return %[4]s.AliasesOf(%[3]s) }

// HasAlias reports whether alias belongs to %[3]s (compared case-insensitively).
func (%[3]s %[2]s) HasAlias(alias string) bool { return %[4]s.HasAlias(%[3]s, alias) }

// Parse%[2]s resolves a canonical name or alias to a %[2]s value,
// case-insensitively. It returns an error wrapping goenum.ErrUnknownEnum for
// unknown names.
func Parse%[2]s(name string) (%[2]s, error) {
	v, ok := %[4]s.Lookup(name)
	if !ok {
		return %[6]s, fmt.Errorf("%%w: %%q for %[2]s", goenum.ErrUnknownEnum, name)
	}
	return v, nil
}

// MustParse%[2]s is Parse%[2]s but panics on unknown names. Use it only for
// inputs known to be valid.
func MustParse%[2]s(name string) %[2]s {
	v, err := Parse%[2]s(name)
	if err != nil {
		panic(err)
	}
	return v
}

// %[2]sFromValue converts an underlying value to a %[2]s and reports whether
// it is declared.
func %[2]sFromValue(v %[7]s) (%[2]s, bool) {
	e := %[2]s(v)
	return e, e.IsValid()
}

// MarshalJSON encodes %[3]s as its canonical JSON name. Undeclared values are
// a marshaling error so invalid data never round-trips silently.
func (%[3]s %[2]s) MarshalJSON() ([]byte, error) {
	name, ok := %[4]s.Name(%[3]s)
	if !ok {
		return nil, fmt.Errorf("goenum: cannot marshal undeclared %[2]s value")
	}
	return json.Marshal(name)
}

// UnmarshalJSON decodes a canonical name or alias into %[3]s.
func (%[3]s *%[2]s) UnmarshalJSON(data []byte) error {
	var name string
	if err := json.Unmarshal(data, &name); err != nil {
		return err
	}
	v, err := Parse%[2]s(name)
	if err != nil {
		return err
	}
	*%[3]s = v
	return nil
}

// MarshalText implements encoding.TextMarshaler.
func (%[3]s %[2]s) MarshalText() ([]byte, error) {
	name, ok := %[4]s.Name(%[3]s)
	if !ok {
		return nil, fmt.Errorf("goenum: cannot marshal undeclared %[2]s value")
	}
	return []byte(name), nil
}

// UnmarshalText implements encoding.TextUnmarshaler, accepting canonical
// names and aliases.
func (%[3]s *%[2]s) UnmarshalText(data []byte) error {
	v, err := Parse%[2]s(string(data))
	if err != nil {
		return err
	}
	*%[3]s = v
	return nil
}

// Value implements database/sql/driver.Valuer, storing the underlying value.
func (%[3]s %[2]s) Value() (any, error) {
	if !%[3]s.IsValid() {
		return nil, fmt.Errorf("goenum: cannot store undeclared %[2]s value")
	}
	return %[8]s, nil
}

// Scan implements sql.Scanner, accepting nil, the underlying numeric/string
// type and canonical names or aliases.
func (%[3]s *%[2]s) Scan(src any) error {
	switch v := src.(type) {
	case nil:
		*%[3]s = %[6]s
		return nil
%[9]s	case string:
		return %[3]s.UnmarshalText([]byte(v))
	case []byte:
		return %[3]s.UnmarshalText(v)
	}
	return fmt.Errorf("goenum: cannot scan %%T into %[2]s", src)
}
`, recv, t, recv, info, strConv, zero, e.Underlying, sqlReturn(e), scanIntCase(e))
}

// scanIntCase renders the int64 Scan branch for integer-backed enums only;
// converting int64 to a string type would yield a single rune, not a name.
func scanIntCase(e *Enum) string {
	if e.Kind == KindString {
		return ""
	}
	return `	case int64:
		e := ` + e.TypeName + `(v)
		if !e.IsValid() {
			return fmt.Errorf("goenum: cannot scan value %d into ` + e.TypeName + `", v)
		}
		*` + receiverName(e.TypeName) + ` = e
		return nil
`
}

// sqlReturn renders the driver.Value expression for Valuer.
func sqlReturn(e *Enum) string {
	if e.Kind == KindString {
		return "string(" + receiverName(e.TypeName) + ")"
	}
	return "int64(" + receiverName(e.TypeName) + ")"
}

func renderFlags(b *strings.Builder, e *Enum, recv, info string) {
	t := e.TypeName
	fmt.Fprintf(b, `
// %[2]sKnownMask has one bit for every declared flag.
const %[3]sKnownMask = %[2]s(%[4]s)

// String renders the flag set as canonical names joined with "|", e.g.
// "READ|WRITE". The zero value renders as "0"; undeclared bits render as
// "%[2]s(<bits>)".
func (%[5]s %[2]s) String() string {
	if %[5]s == 0 {
		return "0"
	}
	var out []string
	rest := uint64(%[5]s)
	names := %[6]s.AllNames()
	for i, v := range %[6]s.All() {
		bit := uint64(v)
		if rest&bit != 0 {
			out = append(out, names[i])
			rest &^= bit
		}
	}
	if rest != 0 {
		out = append(out, "%[2]s("+strconv.FormatUint(rest, 10)+")")
	}
	return strings.Join(out, "|")
}

// IsValid reports whether every bit set in %[5]s is a declared flag. The zero
// value (no flags) is valid.
func (%[5]s %[2]s) IsValid() bool {
	return %[5]s&^%[3]sKnownMask == 0
}

// IsEmpty reports whether no flags are set.
func (%[5]s %[2]s) IsEmpty() bool { return %[5]s == 0 }

// Has reports whether every flag in other is set.
func (%[5]s %[2]s) Has(other %[2]s) bool { return %[5]s&other == other }

// Add returns the union of the flags.
func (%[5]s %[2]s) Add(other %[2]s) %[2]s { return %[5]s | other }

// Remove returns the flags without those in other.
func (%[5]s %[2]s) Remove(other %[2]s) %[2]s { return %[5]s &^ other }

// Description returns the description declared for the single flag %[5]s, or
// "" for combinations and undeclared values.
func (%[5]s %[2]s) Description() string { return %[6]s.Description(%[5]s) }

// Aliases returns the aliases declared for the single flag %[5]s.
func (%[5]s %[2]s) Aliases() []string { return %[6]s.AliasesOf(%[5]s) }

// HasAlias reports whether alias belongs to the single flag %[5]s.
func (%[5]s %[2]s) HasAlias(alias string) bool { return %[6]s.HasAlias(%[5]s, alias) }

// Parse%[2]s resolves a "|"-separated list of canonical names or aliases
// (case-insensitive) into a combined flag set. "0" yields the zero value.
func Parse%[2]s(name string) (%[2]s, error) {
	if name == "0" {
		return 0, nil
	}
	var out %[2]s
	for _, part := range strings.Split(name, "|") {
		v, ok := %[6]s.Lookup(strings.TrimSpace(part))
		if !ok {
			return 0, fmt.Errorf("%%w: %%q for %[2]s", goenum.ErrUnknownEnum, part)
		}
		out |= v
	}
	return out, nil
}

// MustParse%[2]s is Parse%[2]s but panics on unknown names.
func MustParse%[2]s(name string) %[2]s {
	v, err := Parse%[2]s(name)
	if err != nil {
		panic(err)
	}
	return v
}

// %[2]sFromValue converts an underlying bit pattern to a %[2]s and reports
// whether every bit is declared.
func %[2]sFromValue(v %[7]s) (%[2]s, bool) {
	e := %[2]s(v)
	return e, e.IsValid()
}

// MarshalJSON encodes the flag set as its String form.
func (%[5]s %[2]s) MarshalJSON() ([]byte, error) {
	if !%[5]s.IsValid() {
		return nil, fmt.Errorf("goenum: cannot marshal undeclared %[2]s value")
	}
	return json.Marshal(%[5]s.String())
}

// UnmarshalJSON decodes a "|"-separated name list into %[5]s.
func (%[5]s *%[2]s) UnmarshalJSON(data []byte) error {
	var name string
	if err := json.Unmarshal(data, &name); err != nil {
		return err
	}
	v, err := Parse%[2]s(name)
	if err != nil {
		return err
	}
	*%[5]s = v
	return nil
}

// MarshalText implements encoding.TextMarshaler.
func (%[5]s %[2]s) MarshalText() ([]byte, error) {
	if !%[5]s.IsValid() {
		return nil, fmt.Errorf("goenum: cannot marshal undeclared %[2]s value")
	}
	return []byte(%[5]s.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (%[5]s *%[2]s) UnmarshalText(data []byte) error {
	v, err := Parse%[2]s(string(data))
	if err != nil {
		return err
	}
	*%[5]s = v
	return nil
}

// Value implements database/sql/driver.Valuer, storing the bit pattern.
func (%[5]s %[2]s) Value() (any, error) {
	if !%[5]s.IsValid() {
		return nil, fmt.Errorf("goenum: cannot store undeclared %[2]s value")
	}
	return int64(%[5]s), nil
}

// Scan implements sql.Scanner.
func (%[5]s *%[2]s) Scan(src any) error {
	switch v := src.(type) {
	case nil:
		*%[5]s = 0
		return nil
	case int64:
		e := %[2]s(v)
		if !e.IsValid() {
			return fmt.Errorf("goenum: cannot scan value %%d into %[2]s", v)
		}
		*%[5]s = e
		return nil
	case string:
		return %[5]s.UnmarshalText([]byte(v))
	case []byte:
		return %[5]s.UnmarshalText(v)
	}
	return fmt.Errorf("goenum: cannot scan %%T into %[2]s", src)
}
`, recv, t, lowerFirst(t), flagMaskLit(e), recv, info, e.Underlying)
}

// flagMaskLit renders the OR of all declared flag bits as a literal.
func flagMaskLit(e *Enum) string {
	parts := make([]string, len(e.Values))
	for i, v := range e.Values {
		parts[i] = v.Lit
	}
	return strings.Join(parts, " | ")
}

// Names returns the canonical names in declaration order.
func (e *Enum) Names() []string {
	out := make([]string, len(e.Values))
	for i, v := range e.Values {
		out[i] = v.Name
	}
	return out
}

// Descs returns the descriptions in declaration order.
func (e *Enum) Descs() []string {
	out := make([]string, len(e.Values))
	for i, v := range e.Values {
		out[i] = v.Desc
	}
	return out
}

func writeStrings(b *strings.Builder, ss []string) {
	for i, s := range ss {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(strconv.Quote(s))
	}
}

func hasAny(e *Enum, pred func(Value) bool) bool {
	for _, v := range e.Values {
		if pred(v) {
			return true
		}
	}
	return false
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = []rune(strings.ToLower(string(r[0])))[0]
	return string(r)
}

// receiverName picks a short value-receiver name for a type: Status -> s,
// HTTPStatus -> h.
func receiverName(typeName string) string {
	return lowerFirst(typeName)[:1]
}
