package generator

import (
	"fmt"
	"os"
	"path/filepath"
)

// Options controls a generation run.
type Options struct {
	// Paths are files or directories to scan. Empty means the current
	// directory, matching `goenum generate` under a go:generate directive.
	Paths []string
	// Force overwrites existing generated files. Without it, an existing
	// file whose content already matches is left untouched (no-op) and a
	// file that differs is reported as an error to avoid clobbering manual
	// edits to a file that no longer looks generated.
	Force bool
	// DryRun reports what would change without writing.
	DryRun bool
}

// Result describes one written (or would-be-written) file.
type Result struct {
	Path    string
	Changed bool
}

// Generate scans the given paths, validates every enum declaration found and
// writes one <type>_enum_gen.go file per enum next to its source file.
func Generate(opts Options) ([]Result, error) {
	paths, err := ExpandPaths(opts.Paths)
	if err != nil {
		return nil, err
	}
	enums, err := ParseFiles(paths)
	if err != nil {
		return nil, err
	}
	var results []Result
	for _, e := range enums {
		name, src, err := Render(e, e.Pkg)
		if err != nil {
			return nil, err
		}
		out := filepath.Join(filepath.Dir(e.Source), name)
		old, readErr := os.ReadFile(out)
		switch {
		case readErr == nil && string(old) == string(src):
			results = append(results, Result{Path: out, Changed: false})
			continue
		case readErr == nil && !opts.Force:
			// Existing file differs. Only overwrite it if it is clearly a
			// goenum-generated file; otherwise refuse to clobber user edits.
			if len(old) > 0 && !isGeneratedHeader(old) {
				return nil, fmt.Errorf("goenum: refusing to overwrite %s: not a goenum-generated file (use --force)", out)
			}
		}
		if !opts.DryRun {
			if err := os.WriteFile(out, src, 0o644); err != nil {
				return nil, fmt.Errorf("goenum: write %s: %w", out, err)
			}
		}
		results = append(results, Result{Path: out, Changed: true})
	}
	return results, nil
}

func isGeneratedHeader(b []byte) bool {
	const header = "// Code generated by goenum"
	return len(b) >= len(header) && string(b[:len(header)]) == header
}
